//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Favourite = newFavouriteTable("public", "favourite", "")

type favouriteTable struct {
	postgres.Table

	// Columns
	FavouriteID postgres.ColumnInteger
	ShowID      postgres.ColumnInteger
	UserID      postgres.ColumnInteger

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type FavouriteTable struct {
	favouriteTable

	EXCLUDED favouriteTable
}

// AS creates new FavouriteTable with assigned alias
func (a FavouriteTable) AS(alias string) *FavouriteTable {
	return newFavouriteTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new FavouriteTable with assigned schema name
func (a FavouriteTable) FromSchema(schemaName string) *FavouriteTable {
	return newFavouriteTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new FavouriteTable with assigned table prefix
func (a FavouriteTable) WithPrefix(prefix string) *FavouriteTable {
	return newFavouriteTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new FavouriteTable with assigned table suffix
func (a FavouriteTable) WithSuffix(suffix string) *FavouriteTable {
	return newFavouriteTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newFavouriteTable(schemaName, tableName, alias string) *FavouriteTable {
	return &FavouriteTable{
		favouriteTable: newFavouriteTableImpl(schemaName, tableName, alias),
		EXCLUDED:       newFavouriteTableImpl("", "excluded", ""),
	}
}

func newFavouriteTableImpl(schemaName, tableName, alias string) favouriteTable {
	var (
		FavouriteIDColumn = postgres.IntegerColumn("favourite_id")
		ShowIDColumn      = postgres.IntegerColumn("show_id")
		UserIDColumn      = postgres.IntegerColumn("user_id")
		allColumns        = postgres.ColumnList{FavouriteIDColumn, ShowIDColumn, UserIDColumn}
		mutableColumns    = postgres.ColumnList{ShowIDColumn, UserIDColumn}
	)

	return favouriteTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		FavouriteID: FavouriteIDColumn,
		ShowID:      ShowIDColumn,
		UserID:      UserIDColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
