//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Favourite struct {
	FavouriteID int32 `sql:"primary_key"`
	ShowID      *int32
	UserID      *int32
}
