//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Episode struct {
	EpisodeID    int32 `sql:"primary_key"`
	ShowID       *int32
	Number       *int32
	Title        *string
	Description  *string
	VideoURL     *string
	ThumbnailURL *string
	ReleaseDate  *time.Time
}
